spring:
  profiles:
    active:
    - dev 
---
server:
  port: 18111
spring:
  profiles: dev
  application:
    name: airport-operation-safety-management-cloud
  cloud:
    config:
      fail-fast: true
    consul:
      host: 172.21.0.9
      port: 8500
      discovery:
        # instanceId: ${spring.application.name}:${server.port}:${random.value}
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
feign:
  hystrix:
    enabled: true
zuul-address: http://dn1.bid.bds.com:9527/

---
server:
  port: 18111
spring:
  profiles: test
  application:
    name: airport-operation-safety-management-cloud
  cloud:
    config:
      fail-fast: true
    consul:
      host: localhost
      port: 8500
      discovery:
        # instanceId: ${spring.application.name}:${server.port}:${random.value}
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
feign:
  hystrix:
    enabled: true
# zuul-address: http://192.168.0.116:9527/
zuul-address: http://192.168.0.113:9527/