spring:
  profiles:
    active:
    - dev 
---
server:
  port: 9527
spring:
  profiles: dev
  application:
    name: airport-microservice-zuul-gateway
  instance:
    instance-id: airport-microservice-zuul-gateway
    prefer-ip-address: true
  consul:
    host: hadoop01
    port: 8500
    discovery:
      register: true
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
      healthCheckPath: /actuator/health
      healthCheckInterval: 5s
zuul-address: http://hadoop01:9527/
# zuul:
#   routes:
#     # user-service:
#     #   path: /microservicecloud-dept/**
#     #   serviceId: user-service2
#     mydept.serviceId: airport-microservice-flight-info
#     mydept.path: /flight/**
#   ignored-services: '*'
#   #公共前缀
#   prefix: /airport
#   #示例http://localhost:9527/airport/flight/home

info:
  app.name: airport-microservice-gateway
  company.name: www.maplecloudy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 9527
spring:
  profiles: test
  application:
    name: microservicecloud-zuul-gateway
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
  consul:
    host: localhost
    port: 8500
    discovery:
      register: true
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
      healthCheckPath: /actuator/health

# zuul:
#   routes:
#     # user-service:
#     #   path: /microservicecloud-dept/**
#     #   serviceId: user-service2
#     mydept.serviceId: airport-microservice-flight-info
#     mydept.path: /flight/**
#   ignored-services: '*'
#   #公共前缀
#   prefix: /airport

# info:
#   app.name: airport-microservice-gateway
#   company.name: www.maplecloudy.com
#   build.artifactId: $project.artifactId$
#   build.version: $project.version$