spring:
  profiles:
    active:
    - dev 
---
server:
  port: 18080
spring:
  profiles: dev
  application:
    name: airport-microservice-consumer-dev
feign:
  hystrix:
    enabled: true
spring:
  cloud:
    config:
      fail-fast: true
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${server.port}:${random.value}
        healthCheckPath: /health
        healthCheckInterval: 5s

---
server:
  port: 18081
spring:
  profiles: test
  application:
    name: airpor-microservice-consumer-test
feign:
  hystrix:
    enabled: true
spring:
  cloud:
    config:
      fail-fast: true
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${server.port}
        healthCheckPath: /health
        healthCheckInterval: 5s
