spring:
  profiles:
    active:
    - dev 
---
server:
  port: 80
spring:
  profiles: dev
  application:
    name: airport-microservice-consumer-dev
  cloud:
    config:
      fail-fast: true
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${server.port}:${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
feign:
  hystrix:
    enabled: true
  

---
server:
  port: 80
spring:
  profiles: test
  application:
    name: airport-microservice-consumer-test
  cloud:
    config:
      fail-fast: true
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${server.port}
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
feign:
  hystrix:
    enabled: true

