server:
  port: 18080

feign:
  hystrix:
    enabled: true

spring:
  cloud:
    config:
      fail-fast: true
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${server.port}:${random.value}
        healthCheckPath: /health
        healthCheckInterval: 5s

