spring:
  profiles:
    active:
    - dev 
---
server:
  port: 9527
spring:
  profiles: dev
  application:
    name: microservicecloud-zuul-gateway
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
  consul:
    host: localhost
    port: 8500
    discovery:
      register: true
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
      healthCheckPath: /actuator/health

zuul:
  routes:
    # user-service:
    #   path: /microservicecloud-dept/**
    #   serviceId: user-service2
    mydept.serviceId: airport-microservice-flight-info-dev
    mydept.path: /fligth/**
  ignored-services: '*'
  #公共前缀
  prefix: /airport

info:
  app.name: airport-microservice-gateway
  company.name: www.maplecloudy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 9527
spring:
  profiles: test
  application:
    name: microservicecloud-zuul-gateway
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
  consul:
    host: localhost
    port: 8500
    discovery:
      register: true
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
      healthCheckPath: /actuator/health

zuul:
  routes:
    # user-service:
    #   path: /microservicecloud-dept/**
    #   serviceId: user-service2
    mydept.serviceId: airport-microservice-flight-info-dev
    mydept.path: /fligth/**
  ignored-services: '*'
  #公共前缀
  prefix: /airport

info:
  app.name: airport-microservice-gateway
  company.name: www.maplecloudy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$